// Scene Unfolding Machine v8.0 Rev2 — every table, grouped by the book's own sections.
// Rows are [min, max, text]. Lower results favour the protagonists; higher bring trouble.
// That ordering IS the Rule of Bias and must never be re-sorted.

export const BIAS_NOTE =
  "Lower rolls favour the protagonists. Neutral? Roll once. Expecting good? Roll twice, keep the lowest. Expecting bad? Keep the highest.";

export const SUM_SECTIONS = [
  { id: "controller", name: "Scene: Controller", page: 4, kind: "scene" },
  { id: "exploration", name: "Scene: Exploration", page: 5, kind: "scene" },
  { id: "battle", name: "Scene: Battle", page: 6, kind: "scene" },
  { id: "discovery", name: "Scene: Discovery", page: 7, kind: "scene" },
  { id: "first-contact", name: "Character: First contact", page: 8, kind: "character" },
  { id: "shallow", name: "Character: Shallow interaction", page: 9, kind: "character" },
  { id: "trust", name: "Character: Trust conversation", page: 10, kind: "character" },
  { id: "deep", name: "Character: Deep relationship", page: 11, kind: "character" },
];

export const SUM_TABLES = [
  // --- Scene emulation: Controller (p.4) ---------------------------------
  {
    id: "scene-opener", section: "controller", name: "Scene opener", die: 20, page: 4,
    lead: "The GMe asks you to...",
    blurb: "Stuck at the start, or would rather not decide? Let the opener choose your focus.",
    bias: "Keep the lowest if things are relatively normal. Keep the highest if odd things are expected.",
    rows: [
      [1, 2, "Describe the current location, what characters see"],
      [3, 3, "Explain what is going on, the activity in the area"],
      [4, 4, "Review characters' plans — what were they doing?"],
      [5, 5, "Show who else is nearby, or who was here recently"],
      [6, 6, "Depict one particular object that calls their attention"],
      [7, 7, "Recall a detail about the world, its history and features"],
      [8, 8, "Highlight one protagonist to take the spotlight"],
      [9, 10, "Take a look at the weather or atmospheric conditions"],
      [11, 12, "Remind us what exactly brought the characters here"],
      [13, 13, "Mention a potential or imminent danger nearby"],
      [14, 14, "Describe a sensory effect — smells, sounds, or feeling"],
      [15, 15, "Foreshadow what is about to happen in this place"],
      [16, 16, "Consider the possibility of something hiding or secret"],
      [17, 17, "Show an item that could be very useful in the scene"],
      [18, 18, "Highlight a skill or ability that could be helpful now"],
      [19, 20, "Indicate what or whom characters might interact with"],
    ],
  },
  {
    id: "intervention", section: "controller", name: "Intervention check", die: 100, page: 4,
    lead: "The GMe...",
    blurb: "Roll when the PCs are taking too long, tension is high, danger is near, or silence lingers.",
    bias: "Expecting peaceful action? Keep the lowest. For bad news, keep the highest.",
    rows: [
      [1, 20, "Remains silent — nothing really happens (peaceful)"],
      [21, 22, "Describes an additional element or sensory detail"],
      [23, 24, "Puts a helpful item like a note, a key, or instructions"],
      [25, 26, "Gives a single character a chance to shine"],
      [27, 28, "Last action or decision was a good idea, because..."],
      [29, 30, "Something favorable happens — good luck, a relief"],
      [31, 32, "Refers to an object that can be interacted with"],
      [33, 34, "Lays out a suitable or useful item for a character"],
      [35, 36, "Places a clue, lead, or proof that helps a thread"],
      [37, 38, "Reveals something not seen or present earlier"],
      [39, 40, "Places an element of interest behind a challenge"],
      [41, 42, "Shows an element that reflects one world aspect"],
      [43, 44, "Brings someone known or familiar to interact with"],
      [45, 46, "Introduces someone new, helpful for the mission"],
      [47, 48, "Shows proof that confirms an open lead or idea"],
      [49, 50, "Points to an object that reflects the past or history"],
      [51, 70, "Remains silent — nothing seems to happen (tension)"],
      [71, 72, "Shows someone in trouble, needing immediate help"],
      [73, 74, "Throws an issue that requires immediate attention"],
      [75, 76, "Forces a tough call between two options"],
      [77, 78, "Last action or decision was a bad idea, because..."],
      [79, 80, "Something bad happens — misfortune, cause for concern"],
      [81, 82, "Change in location conditions interrupts everybody"],
      [83, 84, "Something breaks, fails, or is damaged around here"],
      [85, 86, "Suddenly puts characters in danger, tension, or risk"],
      [87, 88, "Shows recent deeds of those who want to stop you"],
      [89, 90, "Brings someone to block the characters' progress"],
      [91, 92, "Reflects bad news triggered by a distant event"],
      [93, 94, "Lays out environmental hazards or dangerous traps"],
      [95, 96, "Brings an inconvenient actor into the current scene"],
      [97, 98, "Reveals enemies yet unaware of the protagonists"],
      [99, 100, "Active opposition — enemies show up for conflict"],
    ],
  },
  {
    id: "scene-closure", section: "controller", name: "Scene closure", die: 20, page: 4,
    lead: "Fortunately / unfortunately...",
    blurb: "Use towards the end of a scene to see how the world responds — a consequence, a shift, or a lead into what comes next.",
    bias: "Keep the lowest if luck is on their side; keep the highest if it isn't.",
    rows: [
      [1, 3, "That is, in fact, good — things become easier to achieve"],
      [4, 4, "This is an excellent idea, because of the side effects..."],
      [5, 5, "This was perfectly timed, or with a good coincidence"],
      [6, 6, "Someone else is going to be very happy about this"],
      [7, 7, "Lucky day — characters rewarded, find loot or treasure"],
      [8, 8, "Good call — characters learn or make a breakthrough"],
      [9, 9, "Someone else does the same, or something similar"],
      [10, 10, "This causes a faction to act, make a move, or give aid"],
      [11, 11, "They might want to reconsider that — it's not too late"],
      [12, 12, "Not so fast, someone overlooked something bad..."],
      [13, 13, "They are not going to like what characters are doing"],
      [14, 14, "What characters did risks a bad consequence"],
      [15, 15, "What characters are doing is going to face opposition"],
      [16, 16, "Something else happens while characters try that"],
      [17, 17, "It turns out this won't be possible at all, because..."],
      [18, 20, "That was a bad move — now things get much harder"],
    ],
  },

  // --- Scene emulation: Exploration (p.5) --------------------------------
  {
    id: "location-features", section: "exploration", name: "Location features", die: 20, page: 5,
    lead: "An area that...",
    blurb: "Exploring unknown regions? This oracle inspires unique and distinctive locations.",
    bias: "Lower leans peaceful and informative; higher tends dangerous and exotic.",
    rows: [
      [1, 1, "Encourages introspection or reveals personal truths"],
      [2, 2, "Signs of past habitation or activity, now decayed"],
      [3, 3, "Hidden information, concealed passages, cryptic marks"],
      [4, 4, "Crossroads, junctions, or points with multiple routes"],
      [5, 5, "A resource, power source, or object with capabilities"],
      [6, 6, "An external force manipulating or observing the area"],
      [7, 7, "A meeting point where diverse factions interact"],
      [8, 8, "Residual energy or physical signs of a past struggle"],
      [9, 9, "A transition point between distinct environments"],
      [10, 10, "Peculiar absence of typical sounds or movement"],
      [11, 11, "Darkness or obscurity that conceals hidden dangers"],
      [12, 12, "Being watched or protected by an unseen entity"],
      [13, 13, "A place of balance between opposing forces"],
      [14, 14, "Disrupted, confusing location, giving odd feelings"],
      [15, 15, "Unnatural or inexplicable oddity, object, or presence"],
      [16, 16, "Produces mental fatigue, tiredness, or headaches"],
      [17, 17, "Source of power, energy, electricity, or magic flows"],
      [18, 18, "Corrupted or tainted place with dark reflections"],
      [19, 19, "Contaminated area or zone, physically harmful"],
      [20, 20, "Zone of imminent danger — a sense of exposure"],
    ],
  },
  {
    id: "core-challenge", section: "exploration", name: "Core challenge", die: 20, page: 5,
    lead: "It involves...",
    blurb: "Scenes are shaped by interaction — a test of ability, an obstacle, a moment to act.",
    bias: "Lower is more peaceful and allows time; higher demands urgency and involves danger.",
    rows: [
      [1, 1, "Focus on characters' strengths — they are ready for it"],
      [2, 2, "Detect, spot, perceive — attention and reflexes"],
      [3, 3, "Pilot, drive, mount, handle, or control a device"],
      [4, 4, "Lead, inspire, motivate — time for charisma"],
      [5, 5, "Trace footsteps, survive, or scavenge opportunity"],
      [6, 6, "Lore, know, decipher, translate, or deal with a puzzle"],
      [7, 7, "Repair, fortify, reinforce, restore, or apply mechanics"],
      [8, 8, "Athletics test — crawl, climb, swim, or sprint"],
      [9, 9, "Setting-specific challenge (magic, hacking, crafts)"],
      [10, 10, "Unlock, break, hack, or deal with a complex mechanism"],
      [11, 11, "Heal, aid, support, help, or assist someone quickly"],
      [12, 12, "Dodge, jump, evade — acrobatics and agility test"],
      [13, 13, "Spirit, willpower, courage, wits — a test for the mind"],
      [14, 14, "Resist, endure — fortitude test, physical strain"],
      [15, 15, "Move quickly, hurry — speed and time matter"],
      [16, 16, "Guards or security present — stealth, sneak, steal"],
      [17, 17, "Push, kick, smash, pull, or lift something heavy"],
      [18, 18, "Taunt, intimidate, or confront someone tough-minded"],
      [19, 19, "Outnumbered — can't go frontal, overwhelmed"],
      [20, 20, "Focus on characters' weaknesses — the unexpected"],
    ],
  },
  {
    id: "challenge-conditions", section: "exploration", name: "Challenge conditions", die: 20, page: 5,
    lead: "Consider that...",
    blurb: "The main challenge can always carry an extra layer of tension.",
    bias: "Lower creates peaceful circumstances; higher puts characters in direct danger.",
    rows: [
      [1, 1, "No particular circumstance — easy or straightforward"],
      [2, 2, "Easier if characters have the right tools"],
      [3, 3, "Needs wealth or resources — being rich helps a lot"],
      [4, 4, "Inconveniently located — uncomfortable position"],
      [5, 5, "Involves a puzzle and logic in between"],
      [6, 6, "Needs help or cooperation — cannot be solved alone"],
      [7, 7, "Difficult terrain — geographic obstacles for everyone"],
      [8, 8, "Will take time or work — can't be done immediately"],
      [9, 9, "Someone watching — security or monitor presence"],
      [10, 10, "Haste is rewarded — time, speed, and accuracy"],
      [11, 11, "Involves machinery or dealing with technology"],
      [12, 12, "Time limit — only one chance, or a last attempt"],
      [13, 13, "Visibility issues — lack of information to decide"],
      [14, 14, "Distracting elements, atmospheric difficulties"],
      [15, 15, "Must be done silently, swiftly, and unnoticed"],
      [16, 16, "Could harm characters' reputation or fame"],
      [17, 17, "The enemy may already be aware of the characters"],
      [18, 18, "Poison, hazards, or radiation pose a big problem"],
      [19, 19, "Annoying presence — someone very inconvenient"],
      [20, 20, "Could cause harm, or be extremely painful to try"],
    ],
  },

  // --- Scene emulation: Battle (p.6) -------------------------------------
  {
    id: "terrain-features", section: "battle", name: "Terrain features", die: 20, page: 6,
    lead: "The field contains...",
    blurb: "The battlefield layout can turn a regular fight into an epic one.",
    bias: "Lower has minimal impact; higher can drastically alter the fight.",
    rows: [
      [1, 1, "Plain area with no particular features — easy movement"],
      [2, 2, "Large area to cover — slow to move through"],
      [3, 3, "Vision-impaired zone — fog, heavy rain, or limitations"],
      [4, 4, "Doors, windows, tunnels, or other passageways"],
      [5, 5, "Elevation, steep inclines, or vertical obstacles"],
      [6, 6, "Slow terrain — geographical difficulty"],
      [7, 7, "Physical obstacles, debris, or some obstruction"],
      [8, 8, "Trenches, excavations, or underground paths"],
      [9, 9, "Slippery, wet, flooded, or fully submerged"],
      [10, 10, "Impassable terrain — fully blocked or barricaded"],
      [11, 11, "Distracting forces — requires concentration and focus"],
      [12, 12, "Narrow or too tight — difficult for larger entities"],
      [13, 13, "Unstable ground — changing, moving unpredictably"],
      [14, 14, "Moving, flying, swinging, or alternating elements"],
      [15, 15, "Damaged, failing, unrecoverable — in a broken state"],
      [16, 16, "Danger of falling — visibly unreliable, barely holding"],
      [17, 17, "Hazardous terrain — painful or harmful to cross"],
      [18, 18, "Invisible dangers — known but undetectable"],
      [19, 19, "Something on fire — ongoing, harsh, or changing effect"],
      [20, 20, "Explosive hazards — radioactive or poisonous zone"],
    ],
  },
  {
    id: "enemy-tactics", section: "battle", name: "Enemy tactics", die: 20, page: 6,
    lead: "They seem to...",
    blurb: "How the enemy behaves, and their deployment strategy.",
    bias: "Lower is neutral; higher creates tighter situations or gives enemies the advantage.",
    rows: [
      [1, 1, "Poor, exposed strategy — leaves characters vulnerable"],
      [2, 2, "Large blocks of cover — protective obstacles in use"],
      [3, 3, "Use doors, transitions, tunnels, passages, or trenches"],
      [4, 4, "Area with falling or climbing requirements"],
      [5, 5, "Flanking spots — side positioning or distance matters"],
      [6, 6, "Machinery, special devices, or tech could be used"],
      [7, 7, "Immobilizing traps, alchemy, or field control tactics"],
      [8, 8, "Central strategic position — capture-the-flag scenario"],
      [9, 9, "Moving platforms or transport-based elements"],
      [10, 10, "Attackers have the higher and better position"],
      [11, 11, "Defenders hold the advantage and better position"],
      [12, 12, "They are protecting a key member of their group"],
      [13, 13, "Limited escape routes — risk of being trapped"],
      [14, 14, "Pressing time limit — a bomb, or an imminent threat"],
      [15, 15, "Bystanders or innocents involved — potential hostages"],
      [16, 16, "Expecting reinforcements, or already calling for them"],
      [17, 17, "Protecting an object or key means to win the fight"],
      [18, 18, "Explosive traps, suppression fire, intimidating force"],
      [19, 19, "Possibly setting up an ambush or hidden position"],
      [20, 20, "Mounted weapons, strong defensive stance"],
    ],
  },
  {
    id: "enemy-composition", section: "battle", name: "Enemy composition", die: 20, page: 6,
    lead: "Consider that...",
    blurb: "How your opponents emerge in battle, when little is known about them.",
    bias: "Lower reveals neutral, informative traits; higher indicates more challenging foes.",
    rows: [
      [1, 1, "They have a mix of melee and ranged units"],
      [2, 2, "All of them are melee or close-quarters specialists"],
      [3, 3, "All of them are ranged, using long-distance weapons"],
      [4, 4, "Overwhelming in numbers but significantly weak"],
      [5, 5, "Few in number but highly skilled and diverse"],
      [6, 6, "Immune to one damage type, vulnerable to another"],
      [7, 7, "They begin buffed — start or arrive well-prepared"],
      [8, 8, "Some can hide to ambush or attempt to flank"],
      [9, 9, "Some may use toxins, flasks, or potions"],
      [10, 10, "Some can fly, swim, move fast, or sneak in"],
      [11, 11, "They use area-of-effect weapons or items"],
      [12, 12, "They have an important healer or support unit"],
      [13, 13, "One excels at grappling and closing in combat"],
      [14, 14, "One is particularly well-equipped or shielded"],
      [15, 15, "One is special — has powers, tech, or magic"],
      [16, 16, "One possesses something that could easily cripple"],
      [17, 17, "One can summon or call in new allies"],
      [18, 18, "A dedicated protector or champion leads the way"],
      [19, 19, "They all have very powerful weapons and items"],
      [20, 20, "A story-relevant boss or major foe is participating"],
    ],
  },

  // --- Scene emulation: Discovery (p.7) ----------------------------------
  {
    id: "type-of-clue", section: "discovery", name: "Type of clue", die: 20, page: 7,
    lead: "It presents in the form of...",
    blurb: "What kind of information is uncovered, and how it presents itself.",
    bias: "The higher the result, the more disruptive, dangerous, or esoteric the finding.",
    rows: [
      [1, 1, "Informally written notes, scraped notepads, or a journal"],
      [2, 2, "Tools and other disposable leftovers, a place of work"],
      [3, 3, "Formal or official documents, messages, or letters"],
      [4, 4, "Public communication — rumors, posters, media, film"],
      [5, 5, "Drawings, graffiti, paintings, visual curiosities"],
      [6, 6, "Personal item with someone's distinctive markings"],
      [7, 7, "A reporting spy, agent, or helpful informant"],
      [8, 8, "Maps, coordinates, instructions, plans, next moves"],
      [9, 9, "A damaged or recently used object or vehicle"],
      [10, 10, "An innocent witness, dying enemy, or talkative person"],
      [11, 11, "Coded message, puzzle, riddle, or locked object"],
      [12, 12, "Footsteps, trails, markings — signs of a presence"],
      [13, 13, "Intentional message directed at you"],
      [14, 14, "Enemy mistake, or someone's overlooked activity"],
      [15, 15, "Recording, whispering, or eavesdropping opportunity"],
      [16, 16, "A fading clue or disappearing piece of information"],
      [17, 17, "Vision, oracle, dreams — esoteric forms and answers"],
      [18, 18, "Signs of violence — blood, spent munitions or arrows"],
      [19, 19, "Found at a corpse, crime scene, or blood spatter"],
      [20, 20, "Someone available for interrogation or questioning"],
    ],
  },
  {
    id: "revealing-finding", section: "discovery", name: "Revealing finding", die: 20, page: 7,
    lead: "The finding is...",
    blurb: "Reveal a scene's key findings when making a plot-related discovery.",
    bias: "The higher the result, the more disruptive it becomes.",
    rows: [
      [1, 1, "Answer one open question about the main plot"],
      [2, 2, "Confirm the current location of a target or enemy"],
      [3, 3, "Confirmation of intel, proof or evidence of a theory"],
      [4, 4, "Discovery that bolsters some hope in others"],
      [5, 5, "Learn the weapons or tactics of the enemy"],
      [6, 6, "Find a key, a password, or an equivalent secret"],
      [7, 7, "Useful object or item that assists characters' goal"],
      [8, 8, "Expose personal relationships or contacts of an enemy"],
      [9, 9, "Possibility to convince or gain someone's help"],
      [10, 10, "Discover names, identities, or allegiances"],
      [11, 11, "Discover a key resource location or power source"],
      [12, 12, "Expose enemies' commonly used routes or schedule"],
      [13, 13, "Uncover a clear enemy weakness or vulnerability"],
      [14, 14, "Imminent enemy movement plans or actions"],
      [15, 15, "Proof that contradicts some previous intel or idea"],
      [16, 16, "Proof of blackmail or a planned betrayal"],
      [17, 17, "Plotting, conspiracy, imminent treason in your group"],
      [18, 18, "Discovery that diminishes the hope of others"],
      [19, 19, "Discovery that causes anger or fury in others"],
      [20, 20, "Finding that causes fear or loss of morale in others"],
    ],
  },
  {
    id: "opposition-activity", section: "discovery", name: "Opposition activity", die: 100, page: 7,
    lead: "Apparently...",
    blurb: "A hint about your enemies or an active opposing faction.",
    bias: BIAS_NOTE,
    rows: [
      [1, 10, "One of them got sick, was cursed, or went mad"],
      [11, 12, "Someone chose to disobey or betray them"],
      [13, 14, "One got injured and needs urgent help"],
      [15, 16, "An object or vehicle is starting to malfunction"],
      [17, 18, "They attempted a milestone but failed"],
      [19, 20, "Intercept their communication or secret plotting"],
      [21, 22, "A message, warning, or call for help is being sent"],
      [23, 24, "A neutral party might be acting under enemy orders"],
      [25, 26, "They arrive to issue demands or make threats"],
      [27, 28, "Allies seem to be targeted by enemy actions"],
      [29, 30, "They are now aware of your plans or next steps"],
      [31, 32, "They prevented something good from happening"],
      [33, 34, "Planning to send someone to stop you directly"],
      [35, 36, "Recruited or significantly increased their forces"],
      [37, 38, "Learned to master a new power, device, or ability"],
      [39, 50, "They are talking with our allies or a neutral party"],
      [51, 62, "Disaster or catastrophe recently struck nearby"],
      [63, 64, "They are relocating or shifting one of their bases"],
      [65, 66, "Some documents went missing, stolen, or lost"],
      [67, 68, "Trying to exploit a weakness or press an advantage"],
      [69, 70, "Certain intelligence is misleading, false, unreliable"],
      [71, 72, "They are spreading propaganda or misinformation"],
      [73, 74, "A dangerous ritual or experiment is underway"],
      [75, 76, "They found a new ally, or secured an alliance"],
      [77, 78, "They acquired a powerful item, resource, or tool"],
      [79, 80, "They are setting up traps or preparing an ambush"],
      [81, 82, "Managed to capture, kidnap, or interrogate an ally"],
      [83, 84, "A murder or significant crime has been committed"],
      [85, 86, "A key location claimed, or about to be taken by force"],
      [87, 88, "Currently sabotaging or disrupting some networks"],
      [89, 90, "They are preparing to interfere, directly or not"],
      [91, 100, "A battle, struggle, or crucial decision is unfolding"],
    ],
  },

  // --- Character emulation: First contact (p.8) --------------------------
  {
    id: "meet-reaction", section: "first-contact", name: "Meet reaction", die: 20, page: 8,
    lead: "They seem to...",
    blurb: "How a character behaves or reacts to your protagonists' presence.",
    bias: "Keep the lowest if the winds favor your PCs. Keep the highest if against them.",
    rows: [
      [1, 1, "Approach and greet you — normally, friendly, openly"],
      [2, 2, "Give a flashy, extrovert, or humorous reaction to you"],
      [3, 3, "Engage you and trigger attraction, flirting, charming"],
      [4, 4, "Act with motivation, high energy, full engagement"],
      [5, 5, "Overreact to your presence — surprised or unprepared"],
      [6, 6, "Display pride, authority, certainty, self-confidence"],
      [7, 7, "Be lost in thought, distracted, deep in their own mind"],
      [8, 8, "Remain neutral, cold, or emotionally detached"],
      [9, 9, "Behave neutrally, very cold, kind of lacking emotions"],
      [10, 10, "Be too busy to recognize your presence, or unaware"],
      [11, 11, "Hide away, avoid direct eye contact, or shy away"],
      [12, 12, "Act nervously, as if watched, or highly cautious"],
      [13, 13, "Feel threatened, showing concern or fear toward you"],
      [14, 14, "Despite disliking you, remain respectful and calm"],
      [15, 15, "Act doubtful, questioning, distrusting, disagreeing"],
      [16, 16, "Give an uncomfortable, cold, or unwelcoming look"],
      [17, 17, "Ignore you intentionally, avoiding any interaction"],
      [18, 18, "Try to leave, or prevent any engagement at all"],
      [19, 19, "Look at you disrespectfully, or with rude manners"],
      [20, 20, "Act defensively, ready for a fight if necessary"],
    ],
  },
  {
    id: "outside-looks", section: "first-contact", name: "Outside looks", die: 20, page: 8,
    lead: "They appear to...",
    blurb: "What can be observed at a distance, before engagement? What does their body reveal?",
    bias: "Keep the lowest for neutral or innocent characters; the highest for more active, relevant or enduring ones.",
    rows: [
      [1, 3, "Be completely normal — nothing extraordinary"],
      [4, 4, "Be exotic, exuberant, and enjoy standing out"],
      [5, 5, "Wear clothes that reflect a clear culture or religion"],
      [6, 6, "Show strong habits, mannerisms, or distinct quirks"],
      [7, 7, "Be passionate and verbose about their current actions"],
      [8, 8, "Be with a child, pet, or someone important to them"],
      [9, 9, "Have a strong dialect or accent that suggests origin"],
      [10, 10, "Be clearly skilled, crafty, with appropriate tools"],
      [11, 11, "Know what they're talking about — educated, informed"],
      [12, 12, "Take special care of a particular possession"],
      [13, 13, "Carry equipment or weapons linked to an organization"],
      [14, 14, "Be obviously scared, paranoid, or in an alert state"],
      [15, 15, "Have tattoos or body markings that voice a viewpoint"],
      [16, 16, "Be enduring medical, psychological, or drug effects"],
      [17, 17, "Be in pain — an injury, curse, or sickness"],
      [18, 20, "Be doing something important, or relevant to others"],
    ],
  },
  {
    id: "filler-talks", section: "first-contact", name: "Filler talks", die: 100, page: 8,
    lead: "They talk about...",
    blurb: "Characters have lives too. What are they discussing, or what's on their mind?",
    bias: "Keep the lowest for friendly or peaceful characters, or the highest for more engaged ones.",
    rows: [
      [1, 10, "The weather, the surroundings, or everyday life"],
      [11, 12, "Pets, animals, or equivalent dependents to protect"],
      [13, 14, "Dreams, aspirations, distant or impossible goals"],
      [15, 16, "What they found funny recently, a very funny joke"],
      [17, 18, "An observation about you, an opinion or reflection"],
      [19, 20, "What they love or hate about living in this place"],
      [21, 22, "Science, technology, a shiny object, a curious item"],
      [23, 24, "Studying, learning, education issues, development"],
      [25, 26, "Their importance and role in the world around them"],
      [27, 28, "Their interests, hobbies, or activities they enjoy"],
      [29, 30, "The future, for better or worse — uncertainty"],
      [31, 32, "The past — how better or worse it was, blame history"],
      [33, 34, "Their culture and tradition, holidays, customs, norms"],
      [35, 36, "A book or media they are currently consuming"],
      [37, 38, "Art, paintings, music, or creative expression"],
      [39, 50, "Gossip, sports, events, or other public discussions"],
      [51, 62, "Their current profession, work, duties, obligations"],
      [63, 64, "Weaknesses or flaws that are bigger than them"],
      [65, 66, "How they're struggling with health issues or pain"],
      [67, 68, "Their family, and how tough or difficult things are"],
      [69, 70, "Local rumors, superstition, myths or whispers"],
      [71, 72, "Romance, relationship troubles, or falling in love"],
      [73, 74, "How difficult it is to lie to others — secrets"],
      [75, 76, "Something they recently ate — was it good or healthy?"],
      [77, 78, "Drinking, getting drunk, drugs, or addictive habits"],
      [79, 80, "Clothes, style, design, appearance — or even yours"],
      [81, 82, "Leaving, traveling, future plans, or adventure ideas"],
      [83, 84, "Troubling events, politics, leaders, or corruption"],
      [85, 86, "Religion, faith, the holy and the sacred duties of all"],
      [87, 88, "A current struggle they're stuck in or dealing with"],
      [89, 90, "Celebration, parties, fun, or about taking a break"],
      [91, 100, "What they fear most — their biggest dangers or worries"],
    ],
  },

  // --- Character emulation: Shallow interaction (p.9) --------------------
  {
    id: "personality-type", section: "shallow", name: "Personality type", die: 20, page: 9,
    lead: "They appear to be...",
    blurb: "Spend more time talking and their personality becomes clearer.",
    bias: "Lower results indicate friendlier traits than higher rolls.",
    rows: [
      [1, 1, "Loyal and supportive, devoted to vows and duties"],
      [2, 2, "Always optimistic, expecting the best in every situation"],
      [3, 3, "Kind and nurturing, always eager to help others"],
      [4, 4, "Energetic, proactive, and excited about everything"],
      [5, 5, "Expressive and communicative, creative and playful"],
      [6, 6, "Funny, sarcastic, joking, rarely taking things seriously"],
      [7, 7, "Curious, always seeking creative solutions and ideas"],
      [8, 8, "Open-minded, focused on the future and big picture"],
      [9, 9, "Very focused, goal-oriented and driven to succeed"],
      [10, 10, "Emotional, enjoys deep conversations, empathetic"],
      [11, 11, "Taking charge, leading, perhaps even inspiring others"],
      [12, 12, "Tactful, polite, skilled at handling people carefully"],
      [13, 13, "Very neutral, striving for harmony or avoiding conflict"],
      [14, 14, "Meticulous, preferring to plan and keep things in order"],
      [15, 15, "Reflective, thoughtful, sometimes shy, or reserved"],
      [16, 16, "Practical, down-to-earth, but can be pessimistic"],
      [17, 17, "Serious type, doesn't seem to enjoy a sense of humor"],
      [18, 18, "Unpredictable, independent, dislikes rules"],
      [19, 19, "Challenging, intimidating, direct, unafraid to speak up"],
      [20, 20, "Resistant, hot-headed, always looking for trouble"],
    ],
  },
  {
    id: "recent-anecdote", section: "shallow", name: "Recent anecdote", die: 100, page: 9,
    lead: "They recently...",
    blurb: "What recent event of significance do they share?",
    bias: "Lower rolls are more innocent occurrences; higher rolls are harder to digest.",
    rows: [
      [1, 10, "Took care of personal matters, private issues, family"],
      [11, 12, "Realized they have a unique skill that changes it all"],
      [13, 14, "Received a message from a distant relative"],
      [15, 16, "Won a contest, bringing unwanted fame and trouble"],
      [17, 18, "Searched for something, but found something else"],
      [19, 20, "Met someone who changed the way they see things"],
      [21, 22, "Found a way to overcome and conquer a major fear"],
      [23, 24, "Were betrayed by someone they deeply trusted"],
      [25, 26, "Did something that forced them to make a choice"],
      [27, 28, "Experienced something no one else would believe"],
      [29, 30, "Survived or avoided an accident, by luck or skill"],
      [31, 32, "Discovered a secret that could change everything"],
      [33, 34, "Finished planning a quest or journey ahead"],
      [35, 36, "Found beloved ones they thought never to find again"],
      [37, 38, "Learned about someone who is coming for them..."],
      [39, 50, "Received orders — more work to do, more of the same"],
      [51, 62, "Participated in an important event or public action"],
      [63, 64, "Had a vision or premonition — something is coming"],
      [65, 66, "Fell in love, changing or abandoning all their plans"],
      [67, 68, "Discovered or created something to solve a problem"],
      [69, 70, "Committed a crime, willingly or unwillingly — it is bad"],
      [71, 72, "Had a party, got drunk, celebrated, enjoyed time"],
      [73, 74, "Took part in a cultural or religious ceremony or ritual"],
      [75, 76, "Went through an important transformation or change"],
      [77, 78, "Started a movement for revolution or against the rule"],
      [79, 80, "Became afflicted by a curse or disease — it's really bad"],
      [81, 82, "Found a secret location filled with new wonders"],
      [83, 84, "Got a promotion, or were assigned a new task or job"],
      [85, 86, "Made a great sacrifice, giving something up"],
      [87, 88, "Performed a heroic act, like defeating a monster"],
      [89, 90, "Played a crucial role in restoring or keeping peace"],
      [91, 100, "Got involved in a fight, battle, skirmish, or trouble"],
    ],
  },
  {
    id: "job-or-profession", section: "shallow", name: "Job or profession", die: 20, page: 9,
    lead: "They are...",
    blurb: "What characters do for a living — professionally, vocationally, or by duty.",
    bias: "Keep the lowest for civilians, or the highest for more important figures.",
    rows: [
      [1, 1, "Regular people, handling common or general tasks"],
      [2, 2, "Out of the system — petty robbers, outlaws, criminals"],
      [3, 3, "Natural resources workers, miners, or farmers"],
      [4, 4, "Nature keepers, animal handlers, druids, or shamans"],
      [5, 5, "Teachers, educators, academy members, or students"],
      [6, 6, "Travelers, explorers, wanderers, survivors, hunters"],
      [7, 7, "Somehow mystic, perhaps magical, visionary, esoteric"],
      [8, 8, "Skilled in a craft, working with tools and expertise"],
      [9, 9, "Writers, scribes, journalists, reporters, seekers"],
      [10, 10, "Educated in history, culture, or anthropological lore"],
      [11, 11, "Capable of medicine, healing, and caring for others"],
      [12, 12, "Pilots, drivers, transporters, runners, or couriers"],
      [13, 13, "Handling administrative tasks — lawyers, accountants"],
      [14, 14, "Priests, clerics, religious or spiritual figures, prophets"],
      [15, 15, "Engaged in commerce, doing business, or trade"],
      [16, 16, "Fixers, organized crime, information brokers, hackers"],
      [17, 17, "Fighters — military-trained, defenders, or guardians"],
      [18, 18, "Academics, researchers, scientists, alchemists"],
      [19, 19, "Diplomats, spies, representatives, or officials"],
      [20, 20, "Leaders, governors, rulers, nobility, political figures"],
    ],
  },

  // --- Character emulation: Trust conversation (p.10) --------------------
  {
    id: "opinion-or-answer", section: "trust", name: "Opinion or answer", die: 20, page: 10,
    lead: "Apparently they...",
    blurb: "Share your characters' plans and watch the reaction — they might have something to say.",
    bias: "For supportive characters keep the lowest; for opposing ones keep the highest.",
    rows: [
      [1, 3, "Like the idea, approve, and will promote it"],
      [4, 4, "Support with a fact that strengthens the idea"],
      [5, 5, "Recall a favorable coincidence, because..."],
      [6, 6, "Can do something in the meantime, help with..."],
      [7, 7, "Provide something that can be of help"],
      [8, 8, "Slightly agree without any strong opinion"],
      [9, 9, "Don't really care — it's all the same to them"],
      [10, 10, "Approve but don't really like how it sounds"],
      [11, 11, "Stay neutral; don't want to get involved at all"],
      [12, 12, "Remind about an overlooked problematic detail"],
      [13, 13, "Propose a different approach, method, or opinion"],
      [14, 14, "Disagree and try to convince you otherwise"],
      [15, 15, "Warn or advise against it, but without opposing"],
      [16, 16, "Warn or even threaten against the proposed idea"],
      [17, 17, "Promise to act against it if the idea moves forward"],
      [18, 20, "Disagree, dislike, and will oppose it however they can"],
    ],
  },
  {
    id: "honesty-check", section: "trust", name: "Honesty check", die: 20, page: 10,
    lead: "It sounds like...",
    blurb: "Honest people, deceitful ones, and outright liars — some very good at it.",
    bias: "Keep the lowest for truthful answers and the highest for dishonesty.",
    rows: [
      [1, 3, "There is no reason for them to be lying; fully honest"],
      [4, 4, "They seem to be telling the full truth, nothing to hide"],
      [5, 5, "They share what they know and remember truthfully"],
      [6, 6, "They have compelling reasons to be telling the truth"],
      [7, 7, "If there is anything wrong, it is clearly unintentional"],
      [8, 8, "If there is anything wrong, it is clearly due to ignorance"],
      [9, 9, "They are telling everything as it is convenient to them"],
      [10, 10, "They are telling everything but avoiding any trouble"],
      [11, 11, "They might be hiding something out of safety"],
      [12, 12, "They are probably hiding something, not telling it all"],
      [13, 13, "There is a chance they are changing a few things"],
      [14, 14, "They look nervous, afraid, or uncomfortable"],
      [15, 15, "What they say is inconsistent — something feels off"],
      [16, 16, "It's clear they aren't telling the real truth at all"],
      [17, 17, "They are clearly changing many aspects of the story"],
      [18, 20, "They are obviously lying and trying to deceive"],
    ],
  },
  {
    id: "plot-contribution", section: "trust", name: "Plot contribution", die: 100, page: 10,
    lead: "The character...",
    blurb: "How they could help or hinder your goals — what they bring to the game.",
    bias: "For helpful or good-disposition characters keep the lowest; otherwise keep the highest.",
    rows: [
      [1, 10, "Provides answers that advance the plot and progress"],
      [11, 12, "Offers to join the protagonists to show a path or help"],
      [13, 14, "Shares common cause with you, gives faction support"],
      [15, 16, "Assists with accommodation, comfort, food, or water"],
      [17, 18, "Makes themselves useful or essential to the mission"],
      [19, 20, "Offers resources or materials that support the cause"],
      [21, 22, "Gives directions or intel on a relevant location"],
      [23, 24, "Grants a meaningful blessing, relief, or inspiration"],
      [25, 26, "Talks about or introduces someone they know"],
      [27, 28, "Knows an item or artifact that can make a difference"],
      [29, 30, "Mentions a useful, dangerous, or wonderful place"],
      [31, 32, "Explains how their story connects to current events"],
      [33, 34, "Shares details about an upcoming event or situation"],
      [35, 36, "Points out a critical resource to secure or sabotage"],
      [37, 38, "Proposes a mutual agreement, a trade, or a deal"],
      [39, 50, "Doesn't contribute much but still tries to help"],
      [51, 62, "Asks for a favor or a task before giving information"],
      [63, 64, "Has useful information but is reluctant to reveal it"],
      [65, 66, "Asks to abandon the protagonists' goal, for a reason"],
      [67, 68, "Refuses to share anything unless convinced or bribed"],
      [69, 70, "Brings a viewpoint that conflicts with your interests"],
      [71, 72, "Has done something that the protagonists won't like"],
      [73, 74, "Reveals allegiance to a conflicting or enemy faction"],
      [75, 76, "Warns that the protagonists' actions lead to disaster"],
      [77, 78, "Remains silent and unhelpful, refuses to support"],
      [79, 80, "Is very upset due to the protagonists' recent actions"],
      [81, 82, "Takes the enemy's side, boasting about their stance"],
      [83, 84, "Reveals a truth that badly twists or thickens the plot"],
      [85, 86, "Immediately calls for help or reinforcements against you"],
      [87, 88, "Threatens or accuses you with serious allegations"],
      [89, 90, "Hurls verbal assaults, taunts, or threatens to fight"],
      [91, 100, "Has the power to stop or significantly hinder the plan"],
    ],
  },

  // --- Character emulation: Deep relationship (p.11) ---------------------
  {
    id: "parallel-matters", section: "deep", name: "Parallel matters", die: 20, page: 11,
    lead: "They also want to...",
    blurb: "Side stories and goals to pursue — personal missions and distractions.",
    bias: "Keep the lowest for introspective characters, or the highest for externalized goals.",
    rows: [
      [1, 2, "Figure things out — their purpose or personal goal"],
      [3, 3, "Develop a skill that requires constant training"],
      [4, 4, "Prove, or find a way to disprove, a theory or belief"],
      [5, 5, "Seek answers to a question that may never be resolved"],
      [6, 6, "Constantly strive for self-improvement and growth"],
      [7, 7, "Redeem or atone for a past mistake — seek forgiveness"],
      [8, 8, "Overcome a fear, phobia, or some limiting weakness"],
      [9, 10, "Fulfill a promise or vow — be honored or recognized"],
      [11, 12, "Find companionship, connection, or perhaps true love"],
      [13, 13, "Find a way to heal a physical or emotional wound"],
      [14, 14, "Recover a lost item of personal significance"],
      [15, 15, "Rescue a loved one who has fallen to the wrong side"],
      [16, 16, "Win an important contest or competition someday"],
      [17, 17, "Attain influence and create a meaningful change"],
      [18, 18, "Deal with or confront a threatening, competing rival"],
      [19, 20, "Become rich, indulge in luxury and material pleasures"],
    ],
  },
  {
    id: "lingering-backstories", section: "deep", name: "Lingering backstories", die: 100, page: 11,
    lead: "The character...",
    blurb: "Adult characters had a life before your game began, and carry marks from it.",
    bias: "For morally good characters keep the lowest; for evil or deeply traumatized ones, the highest.",
    rows: [
      [1, 10, "Was raised in a typical environment without issues"],
      [11, 12, "Was once a rebel who fought against the status quo"],
      [13, 14, "Belongs to a royal family or powerful aristocrats"],
      [15, 16, "Is known or famous — whether for good or bad"],
      [17, 18, "Survived a catastrophe, accident, or natural disaster"],
      [19, 20, "Endured a severe disease, or major health issues"],
      [21, 22, "Always had to rely on themselves, never had help"],
      [23, 24, "Has always been the genius one — nature or science"],
      [25, 26, "Lived as a liar, kept secrets — perhaps even an agent?"],
      [27, 28, "Killed someone once... accidentally? a loved one?"],
      [29, 30, "Forced to choose between saving one life or another"],
      [31, 32, "Always been an outsider, foreigner, or life traveller"],
      [33, 34, "An older sibling, a twin, or a guardian figure"],
      [35, 36, "Raised in an unusual or deeply isolated environment"],
      [37, 38, "Raised in a strict religious or dogmatic environment"],
      [39, 50, "Is part of a large or important faction in the world"],
      [51, 62, "Has a dark or mysterious past... (figure it out later)"],
      [63, 64, "Went through brainwashing, a cult, or extremists"],
      [65, 66, "Mocked or bullied in childhood for being different"],
      [67, 68, "Abandoned or banished, from family or a faction"],
      [69, 70, "Suffered a traumatic failure or a crushing defeat"],
      [71, 72, "Carries on with an addiction: alcohol, drugs, gamble"],
      [73, 74, "Did things as a child no other should have to do"],
      [75, 76, "Witnessed a loved one's death... must avenge?"],
      [77, 78, "Experienced or witnessed mental or physical abuse"],
      [79, 80, "Sacrificed everything for someone else's success"],
      [81, 82, "Imprisoned or accused of a crime... innocent or not?"],
      [83, 84, "Grew up in extreme poverty, knows what hunger is"],
      [85, 86, "Born with a genetic or strange inexplicable mutation"],
      [87, 88, "Committed treason... or was once terribly betrayed"],
      [89, 90, "A victim of a curse, prophecy, or public condemnation"],
      [91, 100, "Once abducted — tortured or forced into suffering"],
    ],
  },
  {
    id: "bonding-relations", section: "deep", name: "Bonding relations", die: 20, page: 11,
    lead: "Brought together...",
    blurb: "What originally brought these characters together — history, rivalry, or a shaping event.",
    bias: "Keep the lowest for a deeper connection, or the highest for lingering tension.",
    rows: [
      [1, 2, "Life-long friends — no need to justify old friendship"],
      [3, 3, "Romance, attraction; a current or past good relationship"],
      [4, 4, "Life-changing help — one rescued the other, life-saving"],
      [5, 5, "Many years together, get along well, it's just fun"],
      [6, 6, "Shared origins — same race, region, or neighborhood"],
      [7, 7, "United by the same beliefs, religion, or ideals"],
      [8, 8, "Family members, or part of the same faction"],
      [9, 10, "Sharing a common personal or voluntary mission"],
      [11, 12, "Appointed to work together, or forced into partnership"],
      [13, 13, "A mentor-student relationship grown up to equals"],
      [14, 14, "Share a bond of duty, loyalty, or strong respect"],
      [15, 15, "Once rivals or enemies, now allies or even friends"],
      [16, 16, "Together due to an unusual event — by chance or fate"],
      [17, 17, "A love-hate relationship, yet somehow still together"],
      [18, 18, "Bound by a debt, money, or simply business"],
      [19, 20, "Because they have no other option — strong ties..."],
    ],
  },
];

// Which tables the app offers as a character's rollable "traits", in book order.
export const CHARACTER_TABLE_IDS = [
  "meet-reaction", "outside-looks", "filler-talks",
  "personality-type", "recent-anecdote", "job-or-profession",
  "opinion-or-answer", "honesty-check", "plot-contribution",
  "parallel-matters", "lingering-backstories", "bonding-relations",
];
